'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Indicadores
    
    '''<summary>
    '''hdf_Usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Usuario As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_Idioma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Idioma As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_Operacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Operacion As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_Operacion_Metrica control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_Operacion_Metrica As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_formulario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_formulario As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_PeriodoEstrategico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_PeriodoEstrategico As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_CronoICT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_CronoICT As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdf_SubCronoICT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_SubCronoICT As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lcl_Descripcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Descripcion As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''lcl_Volver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lcl_Volver As Global.System.Web.UI.WebControls.Localize
    
    '''<summary>
    '''pnl_Registro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_Registro As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lbl_tit_Instrumentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_tit_Instrumentos As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddl_Instrumentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_Instrumentos As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''sqlDS_Instrumentos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_Instrumentos As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''pnl_Indicadores_Estrategicos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_Indicadores_Estrategicos As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''gv_declaraciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_declaraciones As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''sqlDS_Estrategias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS_Estrategias As Global.System.Web.UI.WebControls.SqlDataSource
End Class
